load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "greetingpb_proto",
    srcs = ["greeting.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "greetingpb_go_proto",
    importpath = "github.com/bcr-smoke-test/bcr-smoke-test/go/greetingpb",
    proto = ":greetingpb_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "greetingpb",
    embed = [":greetingpb_go_proto"],
    importpath = "github.com/bcr-smoke-test/bcr-smoke-test/go/greetingpb",
    visibility = ["//visibility:public"],
)
