package com.example.greeter;

import com.example.greeter.proto.GreeterGrpc;
import com.example.greeter.proto.HelloReply;
import com.example.greeter.proto.HelloRequest;
import io.grpc.stub.StreamObserver;

/** gRPC service implementation generated by java_grpc_library. */
public final class GreeterService extends GreeterGrpc.GreeterImplBase {
  @Override
  public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
    responseObserver.onNext(Greeter.reply(request));
    responseObserver.onCompleted();
  }
}
