name: smoke
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: bazel build //...
        run: bazel build //...
      - name: bazel test //...
        run: bazel test //...
      - name: lockfiles unchanged
        run: git diff --exit-code
